# Generated by Django 2.1.2 on 2018-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phoneNo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
