# Generated by Django 2.1.2 on 2018-10-15 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilemodel_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phoneNo',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number is not correct', regex='^[0-9]{10}$')]),
        ),
    ]
